on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Check broken links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check links on site
        uses: yantantether/muffet-action@main
        with:
          url: "https://nhsbsa.github.io/nhsbsa-digital-playbook"
          buffer_size: 8192
          exclude: "assets.nhs.uk/$ nhsbsauk.sharepoint.com www.baeldung.com docs.aws.amazon.com/ec2 www.pluralsight.com dps-gitlab.service.nhsbsa"
          max_connections: 20
          timeout: 30
          header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"
