name: Build static site, deploy, check links

on: 
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build          

      - name: Deploy GH Pages
        if: contains(github.ref, 'main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site/nhsbsa-digital-playbook
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '_redirects'

      - name: Deploy Netlify
        if: contains(github.ref, 'develop')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: netlify
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: yantantether/muffet-action@main
        if: contains(github.ref, 'main')
        with:
          url: "https://nhsbsa.github.io/nhsbsa-digital-playbook"
          buffer_size: 8192
          exclude: "assets.nhs.uk/$ nhsbsauk.sharepoint.com www.baeldung.com docs.aws.amazon.com/ec2 www.pluralsight.com dps-gitlab.service.nhsbsa"
          max_connections: 20
          timeout: 30
          header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"

