name: Run library tests

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          npm ci
          BASE_URL=${{ vars.BASE_URL }} npm run test
